name: Download Artifacts and Commit

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The Tag from the source repository release'
        required: true
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout destination repository
        uses: actions/checkout@v4
        with:
          # Use the PAT for cross-repository permissions
          token: ${{ secrets.ACTIONS_PAT }} 

      - name: Download Release assets
        uses: robinraju/release-downloader@v1.12 # Use a community action for cross-repo download
        with:
          token: ${{ secrets.ACTIONS_PAT }} # Use the PAT
          repository: gbonk/vector-drawing-solar-inverter-charger # Replace with your source repo owner/name
          tag: ${{ inputs.run_id }}
          filename: '*-drawio.xml'
          out-file-path: ./temp # Download To Temp Dir

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Rename and Move Files
        run: |
          SUFFIX='-drawio' ; find ./temp -name "*$SUFFIX.xml" |  sed -e "p;s/$SUFFIX//"  | xargs -n2 mv
          mv ./temp/*.xml ./drawio/

      - name: Commit and push changes
        run: |
          # Add all changes in the downloaded-artifacts directory
          git add drawio
          git commit -m "Syncing release artifacts from source repo run ${{ github.event.inputs.run_id }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }} # Use the PAT for pushing
